//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AUTOR
    {
        public int ID_AUTOR { get; set; }
        public string AUTOR { get; set; }
        public string TELEFONO { get; set; }
        public System.DateTime FEC_NAC { get; set; }
        public string ACTIVO { get; set; }
    }
}
